export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001/api'

export const DEVICES = [
  {
    id: 'iphone-14',
    name: 'iPhone 14',
    type: 'iphone' as const,
    width: 390,
    height: 844,
    statusBarHeight: 47,
    homeIndicatorHeight: 34,
  },
  {
    id: 'iphone-14-pro',
    name: 'iPhone 14 Pro',
    type: 'iphone' as const,
    width: 393,
    height: 852,
    statusBarHeight: 54,
    homeIndicatorHeight: 34,
  },
  {
    id: 'ipad-air',
    name: 'iPad Air',
    type: 'tablet' as const,
    width: 820,
    height: 1180,
    statusBarHeight: 24,
    homeIndicatorHeight: 20,
  },
  {
    id: 'android-pixel',
    name: 'Pixel 7',
    type: 'android' as const,
    width: 393,
    height: 851,
    statusBarHeight: 24,
  },
]

export const COMPONENT_LIBRARY = [
  {
    id: 'text',
    name: 'Text',
    type: 'text' as const,
    category: 'display' as const,
    icon: 'Type',
    description: 'Display text content',
    defaultProperties: {
      text: 'Sample Text',
      multiline: false,
      editable: false,
      selectable: true,
    },
    defaultStyle: {
      layout: {
        display: 'flex' as const,
        position: 'relative' as const,
        flexDirection: 'column' as const,
        justifyContent: 'flex-start' as const,
        alignItems: 'flex-start' as const,
        flexWrap: 'nowrap' as const,
      },
      appearance: {
        backgroundColor: undefined,
        backgroundSize: 'cover' as const,
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat' as const,
        opacity: 1,
        overflow: 'visible' as const,
      },
      spacing: {
        margin: { top: 0, right: 0, bottom: 0, left: 0 },
        padding: { top: 8, right: 8, bottom: 8, left: 8 },
      },
      typography: {
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: '400' as const,
        lineHeight: 1.5,
        textAlign: 'left' as const,
        color: { r: 0, g: 0, b: 0, a: 1 },
        textTransform: 'none' as const,
        textDecoration: 'none' as const,
        letterSpacing: 0,
        wordSpacing: 0,
      },
      effects: {
        transform: {
          translateX: 0,
          translateY: 0,
          scaleX: 1,
          scaleY: 1,
          rotate: 0,
          skewX: 0,
          skewY: 0,
        },
      },
    },
    premium: false,
  },
  {
    id: 'button',
    name: 'Button',
    type: 'button' as const,
    category: 'input' as const,
    icon: 'MousePointer',
    description: 'Interactive button component',
    defaultProperties: {
      title: 'Button',
      type: 'primary',
      size: 'medium',
      disabled: false,
      loading: false,
    },
    defaultStyle: {
      layout: {
        display: 'flex' as const,
        position: 'relative' as const,
        flexDirection: 'row' as const,
        justifyContent: 'center' as const,
        alignItems: 'center' as const,
        flexWrap: 'nowrap' as const,
      },
      appearance: {
        backgroundColor: { r: 59, g: 130, b: 246, a: 1 },
        backgroundSize: 'cover' as const,
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat' as const,
        opacity: 1,
        overflow: 'visible' as const,
        border: {
          width: 0,
          color: { r: 0, g: 0, b: 0, a: 1 },
          style: 'solid' as const,
          radius: 8,
        },
      },
      spacing: {
        margin: { top: 0, right: 0, bottom: 0, left: 0 },
        padding: { top: 12, right: 24, bottom: 12, left: 24 },
      },
      typography: {
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: '600' as const,
        lineHeight: 1.5,
        textAlign: 'center' as const,
        color: { r: 255, g: 255, b: 255, a: 1 },
        textTransform: 'none' as const,
        textDecoration: 'none' as const,
        letterSpacing: 0,
        wordSpacing: 0,
      },
      effects: {
        transform: {
          translateX: 0,
          translateY: 0,
          scaleX: 1,
          scaleY: 1,
          rotate: 0,
          skewX: 0,
          skewY: 0,
        },
      },
    },
    premium: false,
  },
  {
    id: 'textInput',
    name: 'Text Input',
    type: 'textInput' as const,
    category: 'input' as const,
    icon: 'Type',
    description: 'Text input field',
    defaultProperties: {
      placeholder: 'Enter text...',
      value: '',
      type: 'text',
      required: false,
      disabled: false,
    },
    defaultStyle: {
      layout: {
        display: 'flex' as const,
        position: 'relative' as const,
        flexDirection: 'column' as const,
        justifyContent: 'flex-start' as const,
        alignItems: 'stretch' as const,
        flexWrap: 'nowrap' as const,
      },
      appearance: {
        backgroundColor: { r: 255, g: 255, b: 255, a: 1 },
        backgroundSize: 'cover' as const,
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat' as const,
        opacity: 1,
        overflow: 'visible' as const,
        border: {
          width: 1,
          color: { r: 209, g: 213, b: 219, a: 1 },
          style: 'solid' as const,
          radius: 8,
        },
      },
      spacing: {
        margin: { top: 0, right: 0, bottom: 0, left: 0 },
        padding: { top: 12, right: 16, bottom: 12, left: 16 },
      },
      typography: {
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: '400' as const,
        lineHeight: 1.5,
        textAlign: 'left' as const,
        color: { r: 0, g: 0, b: 0, a: 1 },
        textTransform: 'none' as const,
        textDecoration: 'none' as const,
        letterSpacing: 0,
        wordSpacing: 0,
      },
      effects: {
        transform: {
          translateX: 0,
          translateY: 0,
          scaleX: 1,
          scaleY: 1,
          rotate: 0,
          skewX: 0,
          skewY: 0,
        },
      },
    },
    premium: false,
  },
  {
    id: 'image',
    name: 'Image',
    type: 'image' as const,
    category: 'media' as const,
    icon: 'Image',
    description: 'Display images',
    defaultProperties: {
      source: 'https://via.placeholder.com/200x150',
      alt: 'Image',
      resizeMode: 'cover',
    },
    defaultStyle: {
      layout: {
        display: 'flex' as const,
        position: 'relative' as const,
        flexDirection: 'column' as const,
        justifyContent: 'center' as const,
        alignItems: 'center' as const,
        flexWrap: 'nowrap' as const,
      },
      appearance: {
        backgroundColor: { r: 243, g: 244, b: 246, a: 1 },
        backgroundSize: 'cover' as const,
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat' as const,
        opacity: 1,
        overflow: 'hidden' as const,
        border: {
          width: 0,
          color: { r: 0, g: 0, b: 0, a: 1 },
          style: 'solid' as const,
          radius: 8,
        },
      },
      spacing: {
        margin: { top: 0, right: 0, bottom: 0, left: 0 },
        padding: { top: 0, right: 0, bottom: 0, left: 0 },
      },
      effects: {
        transform: {
          translateX: 0,
          translateY: 0,
          scaleX: 1,
          scaleY: 1,
          rotate: 0,
          skewX: 0,
          skewY: 0,
        },
      },
    },
    premium: false,
  },
  {
    id: 'container',
    name: 'Container',
    type: 'container' as const,
    category: 'layout' as const,
    icon: 'Grid',
    description: 'Layout container',
    defaultProperties: {},
    defaultStyle: {
      layout: {
        display: 'flex' as const,
        position: 'relative' as const,
        flexDirection: 'column' as const,
        justifyContent: 'flex-start' as const,
        alignItems: 'stretch' as const,
        flexWrap: 'nowrap' as const,
      },
      appearance: {
        backgroundColor: { r: 255, g: 255, b: 255, a: 1 },
        backgroundSize: 'cover' as const,
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat' as const,
        opacity: 1,
        overflow: 'visible' as const,
        border: {
          width: 1,
          color: { r: 229, g: 231, b: 235, a: 1 },
          style: 'solid' as const,
          radius: 8,
        },
      },
      spacing: {
        margin: { top: 0, right: 0, bottom: 0, left: 0 },
        padding: { top: 16, right: 16, bottom: 16, left: 16 },
      },
      effects: {
        transform: {
          translateX: 0,
          translateY: 0,
          scaleX: 1,
          scaleY: 1,
          rotate: 0,
          skewX: 0,
          skewY: 0,
        },
      },
    },
    premium: false,
  },
]

export const SOCIAL_AUTH_PROVIDERS = [
  {
    id: 'google',
    name: 'Google',
    icon: 'google',
    color: '#4285f4',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    icon: 'facebook',
    color: '#1877f2',
  },
  {
    id: 'github',
    name: 'GitHub',
    icon: 'github',
    color: '#333',
  },
  {
    id: 'twitter',
    name: 'Twitter',
    icon: 'twitter',
    color: '#1da1f2',
  },
]

export const APP_CATEGORIES = [
  { value: 'business', label: 'Business' },
  { value: 'productivity', label: 'Productivity' },
  { value: 'finance', label: 'Finance' },
  { value: 'hr', label: 'HR' },
  { value: 'service', label: 'Service' },
  { value: 'education', label: 'Education' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'custom', label: 'Custom' },
]

export const COMPONENT_CATEGORIES = [
  'layout',
  'input',
  'display',
  'navigation',
  'media',
  'business',
  'advanced',
] as const

export const FIELD_TYPES = [
  { value: 'string', label: 'String' },
  { value: 'text', label: 'Text' },
  { value: 'integer', label: 'Integer' },
  { value: 'decimal', label: 'Decimal' },
  { value: 'boolean', label: 'Boolean' },
  { value: 'date', label: 'Date' },
  { value: 'datetime', label: 'DateTime' },
  { value: 'time', label: 'Time' },
  { value: 'json', label: 'JSON' },
  { value: 'uuid', label: 'UUID' },
  { value: 'email', label: 'Email' },
  { value: 'url', label: 'URL' },
  { value: 'phone', label: 'Phone' },
  { value: 'enum', label: 'Enum' },
  { value: 'file', label: 'File' },
  { value: 'image', label: 'Image' },
  { value: 'password', label: 'Password' },
  { value: 'currency', label: 'Currency' },
  { value: 'location', label: 'Location' },
]

export const TRIGGER_TYPES = [
  'app_start',
  'button_click',
  'form_submit',
  'data_change',
  'timer',
  'screen_load',
  'user_login',
  'user_logout',
  'api_webhook',
  'file_upload',
  'notification_received',
  'location_change',
  'device_shake',
  'background_task',
] as const

export const NODE_TYPES = [
  'action',
  'condition',
  'loop',
  'delay',
  'parallel',
  'merge',
  'api_call',
  'database_query',
  'send_email',
  'send_sms',
  'push_notification',
  'file_operation',
  'data_transform',
  'javascript',
  'webhook',
  'schedule',
  'approval',
  'user_input',
  'end',
] as const

export const DEFAULT_COLORS = [
  '#3B82F6',
  '#10B981',
  '#F59E0B',
  '#EF4444',
  '#8B5CF6',
  '#06B6D4',
  '#84CC16',
  '#F97316',
]

export const ANIMATION_DURATION = {
  fast: 150,
  normal: 300,
  slow: 500,
} as const

export const BREAKPOINTS = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
} as const

export const Z_INDEX = {
  dropdown: 1000,
  overlay: 2000,
  modal: 3000,
  tooltip: 4000,
  toast: 5000,
} as const